/**
 * Render the 1200x630 share card in the site's own world, by screenshotting a
 * real page rather than approximating the design in SVG — the card then cannot
 * drift from the fonts and palette the site actually ships.
 *
 * The old site had no Open Graph image at all, so every link shared on LinkedIn
 * rendered blank.
 *
 *   node scripts/og.mjs
 */
import { chromium } from 'playwright-core';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const OUT = path.join(process.cwd(), 'public');

const CARD = `<!doctype html>
<html><head><meta charset="utf-8">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Anybody:wdth,wght@110,800&family=Martian+Mono:wght@400&display=swap" rel="stylesheet">
<style>
  *{margin:0;box-sizing:border-box}
  body{width:1200px;height:630px;background:#080c16;color:#e8f0fa;overflow:hidden;position:relative;
       font-family:'Anybody',sans-serif}
  canvas{position:absolute;inset:0}
  .veil{position:absolute;inset:0;background:radial-gradient(115% 100% at 8% 45%, #080c16 22%, transparent 74%)}
  .in{position:relative;padding:76px 80px;height:100%;display:flex;flex-direction:column;justify-content:center}
  h1{font-size:82px;line-height:.98;letter-spacing:-.035em;font-weight:800;font-stretch:110%;max-width:15ch}
  h1 em{font-style:normal;color:#ff3d8b}
  p{margin-top:28px;font-family:'Martian Mono',monospace;font-size:17px;letter-spacing:.02em;color:#7389ab;max-width:44ch;line-height:1.7}
  .rule{position:absolute;left:0;right:0;bottom:0;height:3px;
        background:linear-gradient(90deg,#35c4e8 0%,#ff3d8b 46%,transparent 78%)}
  .name{position:absolute;top:52px;left:80px;display:flex;align-items:center;gap:14px;
        font-family:'Martian Mono',monospace;font-size:16px;letter-spacing:.14em;color:#9fb3cd}
</style></head><body>
<canvas id="f" width="1200" height="630"></canvas><div class="veil"></div>
<div class="name">
  <svg width="26" height="26" viewBox="0 0 24 24">
    <path d="M5 6 L12 13 L19 5 M12 13 L4 19 M12 13 L20 18" stroke="rgba(53,196,232,.5)" stroke-width="1.3" fill="none"/>
    <circle cx="5" cy="6" r="2.2" fill="#ff3d8b"/><circle cx="19" cy="5" r="1.6" fill="#35c4e8"/>
    <circle cx="12" cy="13" r="2.8" fill="#ff3d8b"/><circle cx="4" cy="19" r="1.6" fill="#35c4e8"/>
    <circle cx="20" cy="18" r="2.1" fill="#35c4e8"/>
  </svg>IYED MDIMEGH
</div>
<div class="in">
  <h1>Vision, distributed training and <em>retrieval</em> systems that ship.</h1>
  <p>INSAT Tunis &middot; First author, IEEE SMC 2025 &middot; Seven competition prizes</p>
</div>
<div class="rule"></div>
<script>
  const c=document.getElementById('f'),x=c.getContext('2d');
  let s=20260909; const rnd=()=>{s=(s*1664525+1013904223)%4294967296;return s/4294967296;};
  const n=Array.from({length:72},()=>({x:rnd()*1200,y:rnd()*630,r:1+rnd()*2.4,hub:rnd()<0.3}));
  for(let i=0;i<n.length;i++)for(let j=i+1;j<n.length;j++){
    const a=n[i],b=n[j],d=Math.hypot(a.x-b.x,a.y-b.y);
    if(d<145){x.beginPath();x.moveTo(a.x,a.y);x.lineTo(b.x,b.y);
      x.strokeStyle='rgba(53,196,232,'+(0.3*(1-d/145)).toFixed(3)+')';x.lineWidth=.7;x.stroke();}
  }
  for(const p of n){x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fillStyle=p.hub?'#35c4e8':'#ff3d8b';x.globalAlpha=.68;x.fill();}
</script></body></html>`;

async function main() {
  await mkdir(OUT, { recursive: true });
  const browser = await chromium.launch({ channel: 'chrome' });
  const page = await browser.newPage({ viewport: { width: 1200, height: 630 }, deviceScaleFactor: 1 });
  await page.setContent(CARD, { waitUntil: 'networkidle' });
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(600);
  const file = path.join(OUT, 'og.png');
  await page.screenshot({ path: file });
  await browser.close();

  // Provenance, so every shipping raster says how it was made.
  await writeFile(
    path.join(OUT, 'og.png.txt'),
    'Generated by scripts/og.mjs — a headless render of the site\'s own hero world\n' +
      '(Anybody 800 @110 width, Martian Mono, palette #080c16 / #35c4e8 / #ff3d8b,\n' +
      'deterministic node field seeded 20260909). Not an AI-generated image.\n',
    'utf8',
  );
  console.log('  public/og.png  1200x630');
}

main().catch((e) => { console.error(e); process.exit(1); });
